import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins],
	format: 'cjs',
	target: 'es2018',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	drop: prod ? ['console'] : [],
	treeShaking: true,
	outfile: 'main.js',
});

if (prod) {
	await context.rebuild();
	
	// Optional local deploy for development convenience.
	const obsidianPath = process.env.OBSIDIAN_PLUGIN_DIR;
	if (obsidianPath) {
		try {
			if (!fs.existsSync(obsidianPath)) {
				fs.mkdirSync(obsidianPath, { recursive: true });
			}
			fs.copyFileSync('main.js', path.join(obsidianPath, 'main.js'));
			fs.copyFileSync('manifest.json', path.join(obsidianPath, 'manifest.json'));
			fs.copyFileSync('styles.css', path.join(obsidianPath, 'styles.css'));
			console.log('Copied to Obsidian:', obsidianPath);
		} catch (err) {
			console.error('Copy failed:', err.message);
		}
	} else {
		console.log('Build complete. Set OBSIDIAN_PLUGIN_DIR to copy files to a vault.');
	}

	process.exit(0);
} else {
	await context.watch();
}
